### PR TITLE
Rename to StructJuMP

### PR DESCRIPTION
**Pull request by joehuchette**
Renames the module to StructJuMP, ``StochasticModel`` to ``StructuredModel``, and the data ``StructureData``.

### CODE REVIEW

**Comment by joehuchette** [comment]
@mlubin @fqiang @emreyamangil @kibaekkim

**Comment by fqiang** [comment]
@joehuchette perfect. Merge into master please.

**Comment by mlubin** [comment]
Definitely could use a notice mentioning the renaming. StochJuMP has already been cited in papers.

**Comment by joehuchette** [comment]
I added ``StructJuMP was originally known as StochJuMP, and tailored specifically towards two-stage stochastic optimization problems.`` to the README. Is that what you mean @mlubin?

**Comment by mlubin** [comment]
@joehuchette yes

**Comment by joehuchette** [comment]
Closed by 33417ddb54526bda0b70e9f94e8dda2ef40448eb

**Pull request closed without merging**
